server:
  port: ${DL_SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DL_DB_HOST:mysql}:${DL_DB_PORT:3306}/${DL_DB_NAME:digiledger}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: ${DL_DB_USER:root}
    password: ${DL_DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.digiledger: DEBUG

app:
  annual-rate-default: 0.5
